version: '3'
services:
  web:
    image: node:21
    ports:
      - "4000:4000"
    networks:
      - my-network
    volumes:
      - C:/Users/genyu/Desktop/groot-guo.github.io:/usr/groot-guo.github.io:rw

networks:
  my-network:
    driver: bridge
  