services:
  web:
    build: #如果需要基于 Dockerfile 构建镜像，可以指定 build: . （其中.表示当前目录下Dockerfile），也可以指定构建上下文目录和其它构建参数。
      context: ../.docker
      target: builder
    restart: always
    container_name: blog-app
    expose:
      - 4000
    ports:
      -  '4000:4000'
